# Schema for the configuration files of the Search API attachments module.

search_api_attachments.admin_config:
  type: mapping
  label: 'Search API attachments settings'
  mapping:
    extraction_method:
      type: string
      label: 'Extractor Plugin ID'
    tika_extractor_configuration:
      type: mapping
      label: 'Tika extractor configuration'
      mapping:
        java_path:
          type: string
          label: 'Path to java executable'
        tika_path:
          type: string
          label: 'Path to Tika .jar file'
    solr_extractor_configuration:
      type: mapping
      label: 'Solr extractor configuration'
      mapping:
        'solr_server':
          type: string
          label: 'Solr server'
